name: CI

on: 
  workflow_dispatch:
    inputs:
      ssl_flavour_and_version:
        description: 'ssl flavour and version'
        required: true
        default: 'OPENSSL_VERSION=3.2.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: clone
        run: |
          git clone https://github.com/haproxy/haproxy

      - name: build ssl
        run: |
          cd haproxy
          ${{ github.event.inputs.ssl_flavour_and_version }} scripts/build-ssl.sh



